# Generated by Django 2.1.15 on 2022-12-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepointone_app', '0002_auto_20221209_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedata',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='updated_at',
        ),
    ]
