# Generated by Django 2.1.15 on 2022-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepointone_app', '0004_auto_20221209_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
