# Generated by Django 2.1.15 on 2022-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepointone_app', '0005_logindetails_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='emp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
