# Generated by Django 2.1.15 on 2022-12-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepointone_app', '0006_employeedata_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='doj',
            field=models.CharField(max_length=50),
        ),
    ]
